server:
  port: 19094

spring:
  application:
    name: order-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      uri: http://localhost:19091
      name: order-service
      profile: local


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/