server:
  port: 19097

spring:
  application:
    name: ai-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      uri: http://localhost:19091
      name: ai-service
      profile: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/