server:
  port: 19097

spring:
  application:
    name: ai-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      uri: http://localhost:19091
      name: ai-service
      profile: local

#  data:
#    redis:
#      host: localhost
#      port: 6379
#      username: default
#      password: systempass
#
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/ai
#    username: delivery
#    password: delivery777
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_batch_fetch_size: 1000
#    defer-datasource-initialization: true
#
#  sql:
#    init:
#      mode: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh

message: "default"