server:
  port: 19096

spring:
  application:
    name: hub-service

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hub
    username: delivery
    password: delivery777

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/