server:
  port: 19095

spring:
  application:
    name: company-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      uri: http://localhost:19091
      name: company-service
      profile: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh

message: "default message"